[package]
name = "lec_05_struct_rocket_txs_mempool"
version = "0.1.0"
edition = "2021"

[dependencies]
rocket = "0.5.0-rc.1"
serde = { version = "1.0.195", features = ["derive"] }
serde_json = "1.0.111"
bitcoincore-rpc = "0.18.0"